version: "3.4"
services:
    web:
        image: registry.cn-hangzhou.aliyuncs.com/nationalchip/iot-rest:1.0-SNAPSHOT

        #默认绑定到8080端口
        ports:
            - "8080:8080"
        volumes:
            - type: bind
              source: ./
              target: /log
            - type: bind
              source: ./
              target: /config
            - type: bind
              source: ./repo
              target: /repo
        depends_on:
          - db
          - cache
        networks:
            - iot
    db:
        image: mdelapenya/mysql-utf8
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=iot
        networks:
          - iot
    cache:
        image: redis
        networks:
          - iot
networks:
    iot:
        driver:
            bridge